version: '3.8'

services:
  mileage-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - PORT=3001
    env_file:
      - .env
    networks:
      - mileage-network

networks:
  mileage-network:
    driver: bridge
