[phases.setup]
nixPkgs = ["nodejs-20_x", "npm-9_x", "curl"]

[phases.install]
cmds = ["npm ci --frozen-lockfile"]

[phases.build]
cmds = [
    "npm run build",
    "npm prune --production"
]

[start]
cmd = "node api/server.js"

[healthcheck]
cmd = "curl -f http://localhost:3001/health || exit 1"
