[phases.setup]
nixPkgs = ["nodejs-20_x", "npm-9_x", "curl"]

[phases.install]
cmds = ["npm ci --frozen-lockfile"]

[phases.build]
cmds = [
    "npm run build",
    "npm prune --production"
]

[start]
cmd = "npx serve dist -s -l 4173"

[healthcheck]
cmd = "curl -f http://localhost:4173 || exit 1"
