// This file is automatically generated. Do not edit it directly.
import PocketBase from 'pocketbase';

const POCKETBASE_URL = import.meta.env.VITE_POCKETBASE_URL;

// Import the pocketbase client like this:
// import { pb } from "@/integrations/pocketbase/client";

export const pb = new PocketBase(POCKETBASE_URL);